package:
  name: fuma
  version: "3.0.8"

source:
  url: https://github.com/yhoogstrate/fuma/archive/refs/tags/v3.0.8.tar.gz
  sha256: c3a4559c8d56b96c6c09da4409101db19e6c34ac712c0249bc0b7b13b30c4196
  patches:
    - remove-nose-dep.patch

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python <3
    - pip
    - numpy
    - htseq ==0.6.1
  run:
    - python <3
    - numpy
    - htseq ==0.6.1

test:
  imports:
    - fuma

  commands:
    - fuma --help
    - fuma --version

about:
  home: https://github.com/yhoogstrate/fuma/
  license:  GNU General Public License v3 or later (GPLv3+)
  summary: 'FuMa: reporting overlap in RNA-seq detected fusion genes'
