{% set name = "tssv" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 833b2a559f9e3a1ddf36f5202138da65b5f930a4cbe4f142590e590a5c96739a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: The package home page
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Targeted characterisation of short structural variation."
  doc_url: https://tssv.readthedocs.io/en/latest/
  dev_url: https://github.com/jfjlaros/tssv

extra:
  recipe-maintainers:
    - Redmar-van-den-Berg
