{% set version="1.0.0" %}

package:
  name: humid
  version: {{ version }}

source:
  url: https://github.com/jfjlaros/HUMID/archive/v{{ version }}.tar.gz
  sha256: 5b8637ad8a177bcf66abf77cbe9262ca748370bd3cb8dbbac619393e292b1166

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - isa-l
    - libdeflate
  run:
    - isa-l
    - libdeflate

test:
  commands:
    - humid

about:
  home: https://github.com/jfjlaros/HUMID
  summary: HUMID -- High-performance UMI Deduplicator
