{% set version="1.0.1" %}

package:
  name: humid
  version: {{ version }}

source:
  url: https://github.com/jfjlaros/HUMID/releases/download/v{{ version }}/humid-v{{ version }}.tar.gz
  sha256: d7595ec98ed6ba6b0ca9b1b5162b912c66d06866c6deeeba5896c737ba06b374

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - isa-l
    - libdeflate
  host:
    - isa-l
    - libdeflate
  run:
    - isa-l
    - libdeflate

test:
  commands:
    - humid > /dev/null

about:
  home: https://github.com/jfjlaros/HUMID
  license: MIT
  summary: HUMID -- High-performance UMI Deduplicator
